### PR TITLE
 Human translation

### PR DESCRIPTION
**Pull request by alekseynemiro**
Fixed translation of the article about AngularJS.

### CODE REVIEW

**Comment by v-tisip** [comment]
### :white_check_mark: Validation status: partially passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[aspnetcore/tutorials/razor-pages-vsc/model.md](https://github.com/alekseynemiro/Docs.ru-ru/blob/master/aspnetcore/tutorials/razor-pages-vsc/model.md) | :x:Error | [View](https://review.docs.microsoft.com/ru-ru/aspnet/core/tutorials/razor-pages-vsc/model?branch=pr-ru-ru-4) | [Details](#user-content-aspnetcore%2Ftutorials%2Frazor-pages-vsc%2Fmodel.md)
[aspnetcore/client-side/angular.md](https://github.com/alekseynemiro/Docs.ru-ru/blob/master/aspnetcore/client-side/angular.md) | :warning:Warning | [View](https://review.docs.microsoft.com/ru-ru/aspnet/core/client-side/angular?branch=pr-ru-ru-4) | [Details](#user-content-aspnetcore%2Fclient-side%2Fangular.md)
[aspnetcore/publishing/iis.md](https://github.com/alekseynemiro/Docs.ru-ru/blob/master/aspnetcore/publishing/iis.md) | :warning:Warning | [View](https://review.docs.microsoft.com/ru-ru/aspnet/core/publishing/iis?branch=pr-ru-ru-4) | [Details](#user-content-aspnetcore%2Fpublishing%2Fiis.md)
[aspnetcore/hosting/iis-modules.md](https://github.com/alekseynemiro/Docs.ru-ru/blob/master/aspnetcore/hosting/iis-modules.md) | :warning:Warning | [View](https://review.docs.microsoft.com/ru-ru/aspnet/core/hosting/iis-modules?branch=pr-ru-ru-4) | [Details](#user-content-aspnetcore%2Fhosting%2Fiis-modules.md)
[aspnetcore/hosting/windows-service.md](https://github.com/alekseynemiro/Docs.ru-ru/blob/master/aspnetcore/hosting/windows-service.md) | :warning:Warning | [View](https://review.docs.microsoft.com/ru-ru/aspnet/core/hosting/windows-service?branch=pr-ru-ru-4) | [Details](#user-content-aspnetcore%2Fhosting%2Fwindows-service.md)
[aspnetcore/publishing/visual-studio-tools-for-docker.md](https://github.com/alekseynemiro/Docs.ru-ru/blob/master/aspnetcore/publishing/visual-studio-tools-for-docker.md) | :warning:Warning | [View](https://review.docs.microsoft.com/ru-ru/aspnet/core/publishing/visual-studio-tools-for-docker?branch=pr-ru-ru-4) | [Details](#user-content-aspnetcore%2Fpublishing%2Fvisual-studio-tools-for-docker.md)
[aspnetcore/security/key-vault-configuration.md](https://github.com/alekseynemiro/Docs.ru-ru/blob/master/aspnetcore/security/key-vault-configuration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/ru-ru/aspnet/core/security/key-vault-configuration?branch=pr-ru-ru-4) | [Details](#user-content-aspnetcore%2Fsecurity%2Fkey-vault-configuration.md)
[aspnetcore/data/ef-mvc/migrations.md](https://github.com/alekseynemiro/Docs.ru-ru/blob/master/aspnetcore/data/ef-mvc/migrations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/ru-ru/aspnet/core/data/ef-mvc/migrations?branch=pr-ru-ru-4) | [Details](#user-content-aspnetcore%2Fdata%2Fef-mvc%2Fmigrations.md)
[aspnetcore/aspnetcore-2.0.md](https://github.com/alekseynemiro/Docs.ru-ru/blob/master/aspnetcore/aspnetcore-2.0.md) | :warning:Warning | [View](https://review.docs.microsoft.com/ru-ru/aspnet/core/aspnetcore-2.0?branch=pr-ru-ru-4) | [Details](#user-content-aspnetcore%2Faspnetcore-2.0.md)
[aspnetcore/performance/caching/middleware.md](https://github.com/alekseynemiro/Docs.ru-ru/blob/master/aspnetcore/performance/caching/middleware.md) | :warning:Warning | [View](https://review.docs.microsoft.com/ru-ru/aspnet/core/performance/caching/middleware?branch=pr-ru-ru-4) | [Details](#user-content-aspnetcore%2Fperformance%2Fcaching%2Fmiddleware.md)
[aspnetcore/fundamentals/hosting.md](https://github.com/alekseynemiro/Docs.ru-ru/blob/master/aspnetcore/fundamentals/hosting.md) | :warning:Warning | [View](https://review.docs.microsoft.com/ru-ru/aspnet/core/fundamentals/hosting?branch=pr-ru-ru-4) | [Details](#user-content-aspnetcore%2Ffundamentals%2Fhosting.md)
[aspnetcore/aspnetcore-1.1.md](https://github.com/alekseynemiro/Docs.ru-ru/blob/master/aspnetcore/aspnetcore-1.1.md) | :warning:Warning | [View](https://review.docs.microsoft.com/ru-ru/aspnet/core/aspnetcore-1.1?branch=pr-ru-ru-4) | [Details](#user-content-aspnetcore%2Faspnetcore-1.1.md)
[aspnetcore/fundamentals/startup.md](https://github.com/alekseynemiro/Docs.ru-ru/blob/master/aspnetcore/fundamentals/startup.md) | :warning:Warning | [View](https://review.docs.microsoft.com/ru-ru/aspnet/core/fundamentals/startup?branch=pr-ru-ru-4) | [Details](#user-content-aspnetcore%2Ffundamentals%2Fstartup.md)
[README.md](https://github.com/alekseynemiro/Docs.ru-ru/blob/master/README.md) | :white_check_mark:Succeeded | |

<a name="aspnetcore%2Ftutorials%2Frazor-pages-vsc%2Fmodel.md"></a>
### [aspnetcore/tutorials/razor-pages-vsc/model.md](https://github.com/alekseynemiro/Docs.ru-ru/blob/master/aspnetcore/tutorials/razor-pages-vsc/model.md)
 - **Line 12**: **[Error]** Start line 19 exceeds total lines 15 when resolving &quot;[!code-csharp[Main](../../tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie/Models/MovieContext.cs?range=1-12,14-17,19-21)]&quot;

<a name="aspnetcore%2Fclient-side%2Fangular.md"></a>
### [aspnetcore/client-side/angular.md](https://github.com/alekseynemiro/Docs.ru-ru/blob/master/aspnetcore/client-side/angular.md)
 - **Line 57**: **[Warning]** Invalid file link:(~/client-side/angular/_static/angular-solution-explorer.png).
 - **Line 99**: **[Warning]** Invalid file link:(~/client-side/angular/_static/simple-directive.png).
 - **Line 131**: **[Warning]** Invalid file link:(~/client-side/angular/_static/simple-databinding.png).
 - **Line 145**: **[Warning]** Invalid file link:(~/client-side/angular/_static/simple-templates-1.png).
 - **Line 149**: **[Warning]** Invalid file link:(~/client-side/angular/_static/simple-templates-2.png).
 - **Line 163**: **[Warning]** Invalid file link:(~/client-side/angular/_static/simple-expressions.png).
 - **Line 176**: **[Warning]** Invalid file link:(~/client-side/angular/_static/repeater.png).
 - **Line 208**: **[Warning]** Invalid file link:(~/client-side/angular/_static/repeaters2.png).
 - **Line 236**: **[Warning]** Invalid file link:(~/client-side/angular/_static/scope.png).
 - **Line 279**: **[Warning]** Invalid file link:(~/client-side/angular/_static/controllers.png).
 - **Line 305**: **[Warning]** Invalid file link:(~/client-side/angular/_static/components.png).
 - **Line 365**: **[Warning]** Invalid file link:(~/client-side/angular/_static/rest-bound.png).
 - **Line 416**: **[Warning]** Invalid file link:(~/client-side/angular/_static/spa-persons.png).
 - **Line 420**: **[Warning]** Invalid file link:(~/client-side/angular/_static/spa-persons-2.png).
 - **Line 468**: **[Warning]** Invalid file link:(~/client-side/angular/_static/events.png).

<a name="aspnetcore%2Fpublishing%2Fiis.md"></a>
### [aspnetcore/publishing/iis.md](https://github.com/alekseynemiro/Docs.ru-ru/blob/master/aspnetcore/publishing/iis.md)
 - **[Warning]** 1 invalid cross reference(s) &quot;[ведению журналов](xref:fundamentals/logging)&quot;.
 - **Line 43**: **[Warning]** Invalid file link:(~/publishing/iis/_static/windows-features-win10.png).
 - **Line 49**: **[Warning]** Invalid file link:(~/publishing/iis/_static/server-roles-ws2016.png).
 - **Line 53**: **[Warning]** Invalid file link:(~/publishing/iis/_static/role-services-ws2016.png).
 - **Line 149**: **[Warning]** Invalid file link:(~/publishing/iis/_static/add-website-context-menu-ws2016.png).
 - **Line 153**: **[Warning]** Invalid file link:(~/publishing/iis/_static/add-website-ws2016.png).
 - **Line 157**: **[Warning]** Invalid file link:(~/publishing/iis/_static/apppools-basic-settings-ws2016.png).
 - **Line 161**: **[Warning]** Invalid file link:(~/publishing/iis/_static/edit-apppool-ws2016.png).
 - **Line 177**: **[Warning]** Invalid file link:(~/publishing/iis/_static/pub-dialog.png).
 - **Line 186**: **[Warning]** Invalid file link:(~/publishing/iis/_static/browsewebsite.png).
 - **Line 285**: **[Warning]** Invalid file link:(~/publishing/iis/_static/apppool-identity.png).
 - **Line 301**: **[Warning]** Invalid file link:(~/publishing/iis/_static/select-users-or-groups-1.png).
 - **Line 305**: **[Warning]** Invalid file link:(~/publishing/iis/_static/select-users-or-groups-2.png).

<a name="aspnetcore%2Fhosting%2Fiis-modules.md"></a>
### [aspnetcore/hosting/iis-modules.md](https://github.com/alekseynemiro/Docs.ru-ru/blob/master/aspnetcore/hosting/iis-modules.md)
 - **[Warning]** 2 invalid cross reference(s) &quot;[Ведение журнала ASP.NET Core](xref:fundamentals/logging#the-tracesource-provider)&quot;, &quot;[Ведение журнала ASP.NET Core](xref:fundamentals/logging)&quot;.
 - **Line 149**: **[Warning]** Invalid file link:(~/hosting/iis-modules/_static/modules.png).

<a name="aspnetcore%2Fhosting%2Fwindows-service.md"></a>
### [aspnetcore/hosting/windows-service.md](https://github.com/alekseynemiro/Docs.ru-ru/blob/master/aspnetcore/hosting/windows-service.md)
 - **[Warning]** 1 invalid cross reference(s) &quot;[поставщик журнала событий Windows](xref:fundamentals/logging#eventlog)&quot;.
 - **Line 68**: **[Warning]** Invalid file link:(~/hosting/windows-service/_static/create-start.png).
 - **Line 72**: **[Warning]** Invalid file link:(~/hosting/windows-service/_static/running-in-service.png).

<a name="aspnetcore%2Fpublishing%2Fvisual-studio-tools-for-docker.md"></a>
### [aspnetcore/publishing/visual-studio-tools-for-docker.md](https://github.com/alekseynemiro/Docs.ru-ru/blob/master/aspnetcore/publishing/visual-studio-tools-for-docker.md)
 - **Line 39**: **[Warning]** Invalid file link:(~/publishing/visual-studio-tools-for-docker/_static/settings-shared-drives-win.png).
 - **Line 47**: **[Warning]** Invalid file link:(~/publishing/visual-studio-tools-for-docker/_static/project-add-docker-support.png).
 - **Line 51**: **[Warning]** Invalid file link:(~/publishing/visual-studio-tools-for-docker/_static/right-click-add-docker-support.png).

<a name="aspnetcore%2Fsecurity%2Fkey-vault-configuration.md"></a>
### [aspnetcore/security/key-vault-configuration.md](https://github.com/alekseynemiro/Docs.ru-ru/blob/master/aspnetcore/security/key-vault-configuration.md)
 - **[Warning]** 1 invalid cross reference(s) &quot;[инфраструктуры ASP.NET ведения журнала](xref:fundamentals/logging)&quot;.
 - **Line 76**: **[Warning]** Invalid file link:(~/security/key-vault-configuration/_static/sample1.png).
 - **Line 112**: **[Warning]** Invalid file link:(~/security/key-vault-configuration/_static/sample2-1.png).
 - **Line 116**: **[Warning]** Invalid file link:(~/security/key-vault-configuration/_static/sample2-2.png).

<a name="aspnetcore%2Fdata%2Fef-mvc%2Fmigrations.md"></a>
### [aspnetcore/data/ef-mvc/migrations.md](https://github.com/alekseynemiro/Docs.ru-ru/blob/master/aspnetcore/data/ef-mvc/migrations.md)
 - **[Warning]** 1 invalid cross reference(s) &quot;[введение к ведению журнала](xref:fundamentals/logging)&quot;.
 - **Line 65**: **[Warning]** Invalid file link:(~/data/ef-mvc/migrations/_static/open-in-file-explorer.png).
 - **Line 69**: **[Warning]** Invalid file link:(~/data/ef-mvc/migrations/_static/open-command-window.png).
 - **Line 153**: **[Warning]** Invalid file link:(~/data/ef-mvc/migrations/_static/students-index.png).

<a name="aspnetcore%2Faspnetcore-2.0.md"></a>
### [aspnetcore/aspnetcore-2.0.md](https://github.com/alekseynemiro/Docs.ru-ru/blob/master/aspnetcore/aspnetcore-2.0.md)
 - **[Warning]** 1 invalid cross reference(s) &quot;[Введение в ведение журналов](xref:fundamentals/logging)&quot;.

<a name="aspnetcore%2Fperformance%2Fcaching%2Fmiddleware.md"></a>
### [aspnetcore/performance/caching/middleware.md](https://github.com/alekseynemiro/Docs.ru-ru/blob/master/aspnetcore/performance/caching/middleware.md)
 - **[Warning]** 1 invalid cross reference(s) &quot;[входа](xref:fundamentals/logging)&quot;.

<a name="aspnetcore%2Ffundamentals%2Fhosting.md"></a>
### [aspnetcore/fundamentals/hosting.md](https://github.com/alekseynemiro/Docs.ru-ru/blob/master/aspnetcore/fundamentals/hosting.md)
 - **[Warning]** 2 invalid cross reference(s) &quot;[входа](xref:fundamentals/logging)&quot;, &quot;[фильтрации журнала](xref:fundamentals/logging#log-filtering)&quot;.

<a name="aspnetcore%2Faspnetcore-1.1.md"></a>
### [aspnetcore/aspnetcore-1.1.md](https://github.com/alekseynemiro/Docs.ru-ru/blob/master/aspnetcore/aspnetcore-1.1.md)
 - **[Warning]** 1 invalid cross reference(s) &quot;[Поставщик ведения журнала службы приложений Azure](xref:fundamentals/logging#appservice)&quot;.

<a name="aspnetcore%2Ffundamentals%2Fstartup.md"></a>
### [aspnetcore/fundamentals/startup.md](https://github.com/alekseynemiro/Docs.ru-ru/blob/master/aspnetcore/fundamentals/startup.md)
 - **[Warning]** 1 invalid cross reference(s) &quot;[Ведение журнала](xref:fundamentals/logging)&quot;.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C14%5C94704940-3fc2-83f9-2608-a7be0605e140%5CPullRequest%5C201711141654028775-4%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=i%2BQR8WazrvARRH5cPfe4zrnAKZ%2BW3n4WR5jS0E%2B2xrg%3D&st=2017-11-14T16%3A51%3A40Z&se=2017-12-15T16%3A56%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by gosali** [comment]
Hi @alekseynemiro , we are still in discussing, will update the decision later soon. 
  
Thanks for your support,
Microsoft C&E Localization Team

**Comment by gosali** [comment]
Hi @alekseynemiro , we are still in discussing, will update the decision later soon.

Thanks for your support,
Microsoft C&E Localization Team

**Comment by v-maudel** [comment]
Hello, @alekseynemiro ,

 Thank you for your feedback and suggestion. 
 
Unfortunately, we consider that suggestions are not fully aligned with our criteria for acceptance

Closing this PR since it does not apply

Thank you.

Kind regards,
 
Microsoft C&E Localization Team

**Pull request closed without merging**
